config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "home#index"
  get "/pokemon" => "pokemon#index"
  get "/pokemon/volt" => "pokemon#volt"
  post "/pokemon/speed" => "pokemon#speed"

  # get "/posts/my" => "posts#my"
  
  resources :posts do
    collection do
      get :my
    end
    member do  
    end
    resources :like do
      collection do
        get :check
      end
    end
  end

  resources :comments

  resources :instagram do
    collection do
      get :check
      get :check_follow
      get :view
    end
  end
 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional:true
  belongs_to :post, optional:true
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :post, optional: true

  def image_url
    self.image.image_url
  end
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user, optional:true
  belongs_to :post, optional:true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional:true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :nullify
  has_many :likes
  has_many :like_posts, through: :likes, source: :post
  
  # following
  has_many :follows, dependent: :destroy
  has_many :followings, through: :follows, source: :target

  # follower
  has_many :received_follows, class_name: "Follow", foreign_key: :target_id, dependent: :destroy
  has_many :followers, through: :received_follows, source: :user

  mount_uploader :image, ImageUploader


  def liked? post_id=nil
    self.likes.find_by(post_id: post_id).present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      @posts=Post.all
      if current_user
        @user=current_user
        @favorate_posts=Post.where
      else
        @user="게스트"
      end
    end
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
	def index
		if current_user
			array=Array.new
			current_user.follows.each do |f|
				array.push(f.target_id)
			end
			array.push(current_user.id)
			@post=Post.where(user_id:array).order(created_at: :desc)
	
		end
	end
	def new
	
	end

	def create
	
	end

	def update
	
	end
	
	def destroy
	
	end
	
	def edit
	
	end

	def show
		@user=load_user
		@posts=load_post
	end

	def check
		if current_user.present?
			redirect_to destroy_user_session_path, method: delete
		else
			redirect_to new_user_session_path
		end
  end
  
	def view
		@post=load_post_by_id
		@user=load_user_by_post
		respond_to do |format|
			format.html
			format.js
		end
	end
  

	def check_follow
		follow=current_user.follows.find_by(target_id: params[:id])
		
		if follow.present?
			follow.destroy
		else
			Follow.create follow_params
		end
		render 'onload'
  end
  
  private
	def follow_params
		{user_id: current_user.id, target_id:  params[:id]}
  end

  def load_user
		User.find_by(id: params[:id])
  end
	def load_user_by_post
		User.find_by(id: @post.user_id)
	end
  def load_post
		Post.where(user_id: @user.id).order(created_at: :desc)
  end
  def load_post_by_id
		Post.find_by(id: params[:id])
	end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
	def check
		like=current_user.likes.find_by(post_id: params[:post_id])
		
		if like.present?
			like.destroy
			#redirect_to post_path(params[:post_id])
		else
			Like.create like_params
			#redirect_to post_path(params[:post_id])

		end
	end
	private
	def like_params
		{user_id: current_user.id, post_id: params[:post_id]}
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :load_object, only: %i(show edit update destroy)
    before_action :check_user, only: %i(edit destroy update)
    #CRUD 7가지. index, new, show, edit, create, update, destroy
    def index
        @posts=Post.all
        #모든 게시물들을 다 가지고 온다.
    end

    def new
        @post =Post.new
        3.times.each do
            @post.images.build
        end
    end

    def show
       
    end

    def edit
       
    end

    def create
       # post=Post.create params.require(:post).permit(:title,:body,:author)
       post=Post.create post_params 
       redirect_to post_path(post)
    end

    def update
        
        #post.update params.require(:post).permit(:title, :author, :body)
        @post.update post_params
        redirect_to post_path(@post)
    end
    
    def destroy
       @post.destroy
       redirect_to posts_path()
    end

    def my
        @mypost=current_user.posts.all
    end
   
    private
    def post_params
        # 가장 마지막 줄을 return 한다. -> return 생략 가능.
        return params.require(:post).permit(:title,:author, :body, :user_id, images_attributes: [:image])
    end

    def load_object
        @post=Post.find_by(id: params[:id])
    end


    def check_user
        redirect_to root_path if current_user != @post.user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/instagram/_comment.html.erb
<% comments ||= [] %>

<div class="list-group">
  <% if comments.present? %>
    <% comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% else %>
    <div class="list-group-item ">
    </div>
  <% end %>
</div>

app/views/instagram/_form.html.erb
<style>
    .card-inline-item{
        display : flex;
        align-items:center;

    }
    .card-item-margin{
        margin: 0px 14px 0px 0px;
 
    }
    .card-item-button-list{
        margin-top:4px;
        padding-left:16px;
        height: 40px;
    }
    .card-body-like-count-list{
        padding-left:16px;
        margin-bottom:8px;
    }
    .text-bold{
        font-weight:bold;
    }
    .w-32{
			position: relative;
			width: 32px;
			height: 32px;
			overflow: hidden;
    }
    .clip-circle-15 {
			clip-path: circle(15px at center);
			background:red;
    }
    .img-div{
			position: relative;
			width: 614px;
			overflow: hidden;
    }
    .img-inner{
			top: -9999px;
			left: -9999px;
			right: -9999px;
			bottom: -9999px;
			margin: auto;
    }
    .img-resize{
			max-width: 100%;
			max-height: 100%;
			display: block;
    }
    .img-resize-default{
			max-width: 80%;
			max-height: 80%;
			display: block;
    }
    .card-title{
			width:614px;
			padding: 14px 16px 14px 16px;
			margin: 0px;
			border-bottom-width:1px;
		}
    .text-weight{
			font-size:14px;
			font-weight:600;
        
    }
    .text-content-weight{
			font-size:14px;
    }
    .post-content-body-margin{
			align-items:center;
			margin-bottom:4px;
    }
    .card-text{
			padding-left:16px;
    }
		.card-time{
			padding-left:16px;
			text-align:left;
			font-size:10px;
			color:#8e8e8e;
			margin-top:4px;
			margin-bottom:4px;
		}
    .comment-form-style{
			width:614px;
			height:55px;
			border-top: 1px solid rgba(var(--ce3,239,239,239),1);
			padding-left: 16px;
			padding-right: 16px;
			margin-top: 4px;
			display: flex;
			align-items:center;

    }
    .comment-form-body{
			width:530px;
			height:24px;
			border: 0;
			padding:0px;
			outline: 0px;  

			border: none;
			overflow: auto;
			outline: none;

			-webkit-box-shadow: none;
			-moz-box-shadow: none;
			box-shadow: none;

			resize: none; 
    }
    .comment-submit-button-style{
			width:40px;
			height:18px;
			margin:0px;
			padding:0px;
			background:white;
			border-radius: 0px;
			border:none;
			color:blue;
			background-color:white;
			text-align: center;
			color:#0095f6;
			box-shadow:none;
			text-shadow:none;
			line-height:0;
			transition:none;
			text-decoration: none;
    }
    
    form input[type=submit]:not(.disabled):hover, form input[type=button]:not(.disabled):hover, form button:not(.disabled):hover {
			background-color:white;
			background-image:none;
			color:#0095f6;

    }
}
</style>
<div class="card">
    <div class="card-title text-left card-inline-item" >
        <div class="card-item-margin">
            <div class ="user_image card-inline-item w-32">
                <%if user[0].image.present?%>
                    <img src="<%= user[0].image%>" class="d-block img-resize clip-circle-15" alt="">
                <%else%>
                    <img src="<%= "image/user.jpg"%>" class="d-block img-resize-default img-inner clip-circle-15" alt="">
                <%end%>
            </div> 
        </div> 
        <div class="card-item-margin text-weight">
            <!-- user info section -->
            <%=link_to user[0].email, instagram_path(user[0].id), class:"my-user-id-font", style: 'color : black'%>         
        </div>
    </div>
    <div>
        <%if post.images.present?%>
            <div id="carouselExampleIndicators<%=post.id%>" class="carousel slide" data-touch="true">
                <ol class="carousel-indicators">
                    <% post.images.count.times.each do |index| %>
                        <li data-target="#carouselExampleIndicators<%=post.id%>" data-slide-to="<%= index %>" class="<%= 'active' if (index == 0) %>"></li>
                    <% end %>
                </ol>
                <div class="carousel-inner">
                    <% post.images.each_with_index do |image, index| %>
                        <div class="carousel-item img-div <%= 'active' if (index == 0) %>">
                            <img src="<%= image.image %>" class="d-block w-100 img-inner" alt="">
                        </div>
                    <% end %>
                </div>
            </div>
        <%else%>
            <img src="image/instagram.png" class="card-img">
        <%end%>
    </div>
    
    <div class=" card-inline-item card-item-button-list">
        <div class="card_item_margin">
            <!--post like,button section -->
            <% like_btn = '<svg aria-label="좋아요" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>'.html_safe %>
            <% like_btn_fill = '<svg aria-label="좋아요 취소" class="_8-yf5 " fill="#ed4956" height="24" viewBox="0 0 48 48" width="24"><path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>'.html_safe %>
            <%= link_to (current_user.liked?(post.id) ? like_btn_fill : like_btn),  check_post_like_index_path(post), remote:true %>        
        </div>
        <div class="card_item_margin">
            <!--comment-btn -->
        </div>
    </div>
    <div class=" text-left card-body-like-count-list text-weight">
        <!--post like count section -->
        좋아요 <%=Like.where(post_id: post.id).size%>개
    </div>
    <div class="card-text text-left card-inline-item card-item-margin  post-content-body-margin" >
        <div class="text-left text-weight"> 
            <%=link_to user[0].email, instagram_path(user[0].id), class:"my-user-id-font", style: 'color : black'%>         

        </div>
        &nbsp;
        <div class=" text-left text-content-weight">
            <!--post description section -->
            <%= post.body%>
        </div>
    </div>
    
    <div class = "card-text  text-left">
        <%=render 'instagram_comments/comments' , comments: post.comments.order(created_at: :asc)%>
    </div>
		<div class="card-time">
			<%time=TimeDifference.between(Time.now,post.created_at).in_general%>
			<%if time.values[0] != 0%>
				<%=time.values[0]%>년 전
			<% elsif time.values[1]!=0%>
				<%=time.values[1]%>달 전
			<% elsif time.values[2]!=0%>
				<%=time.values[2]%>주 전
			<% elsif time.values[3]!=0%>
				<%=time.values[3]%>일 전
			<% elsif time.values[4]!=0%>
				<%=time.values[4]%>시간 전
			<% elsif time.values[5]!=0%>
				<%=time.values[5]%>분 전
			<% else %>
				<%=time.values[6]%>초 전
			<% end %>
    
		</div>
    <div>
        <%=render 'instagram_comments/form', comment: Comment.new, post:post, user: current_user%>
    </div>
</div>

app/views/instagram/_user.html.erb
<% users ||= [] %>
<% if users.present? %>
    <% users.each do |user| %>
        <div class="follow-user-list">
            <div>
                <%if user.image.present?%>
                    <img src="<%= user.image%>" class="d-block w-32-m clip-circle-16" alt="">
                <%else%>
                    <img src="<%= "image/user.jpg"%>" class="d-block w-32-m clip-circle-16" alt="">
                <%end%>
            </div>
            <div class="my-user-follow">
                <%=link_to user.email, instagram_path(user.id), class:"my-user-id-font", style: 'color : black'%> 

            </div>
            <div class="my-user-id-follow">
                <% if user.present?%>
                    <%= link_to current_user.follows.find_by(target_id: user.id).present? ? '<div class="my-user-id-font-reco-follow">언팔로우</div>'.html_safe : '<div class="my-user-id-font-reco-follow">팔로우</div>'.html_safe, check_follow_instagram_index_path(id: user) , remote:true%>
                <%end%>
            </div>
        </div>
    <% end %>
<% end %>

app/views/instagram/_view.html.erb
<style>
    .modal-total-body{
        width:935px;
        height:600px;
        display:flex;
        padding:0px;
    }
    .modal-total-form-img{
        width:600px;
        height:600px;
    }
    .modal-total-form-info{
        width:335px;
        height:72px;
        padding:16px auto;
        display:flex;
    }
    .modal-total-form-info{
        padding:16px 16px 16px 16px;
        border-bottom:1px solid #0f0f0f36;

    }
    .modal-total-form-info-img{

    }.modal-total-form-info-user{
        font-size:14px;
        font-weight:600;
        align-self:center;
    }
    .modal-total-form-content{
        padding:16px 16px 16px 16px;
        height:388px;
        max-height:388px;
        overflow-y:auto;
        -ms-overflow-style: none;
        
    }
    .modal-total-form-content::-webkit-scrollbar {
        display: none;
    }
    .modal-total-form-content-body{
        display: flex;
        margin-bottom:12px;
    }
    .modal-total-form-content-body-style{
        font-size:14px;
		font-weight: 300;
        margin-left:14px;
        align-self:center;
    }
    .modal-total-form-button{
        height:45px;
    }
    .modal-total-form-like{
        height:30px;
        margin-bottom:8px;
    }
    .modal-total-form-comment{
        height:56px;

    }
    .w-40-m{
    width: 40px!important;
    margin-right:14px;
    height:40px;
    }
    .clip-circle-16 {
        clip-path: circle(16px at center);
    }
</style>

<div class="modal-body modal-total-body">
    <div class="modal-total-form-img">
        <div id="carouselExampleIndicators" class="carousel slide" data-touch="true">
            <ol class="carousel-indicators">
                <% @post.images.count.times.each do |index| %>
                    <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= 'active' if (index == 0) %>"></li>
                <% end %>
            </ol>
            <div class="carousel-inner">
                <% @post.images.each_with_index do |image, index| %>
                    <div class="carousel-item img-div <%= 'active' if (index == 0) %>">
                        <img src="<%= image.image %>" class="d-block w-100 img-inner" alt="">
                    </div>
                    <%= image.image %>
                <% end %>
            </div>
        </div>
    </div>
    <div>
        <div class="modal-total-form-info">
            <div class ="modal-total-form-info-img">
                <img src="<%= current_user.image%>" class="d-block w-40-m clip-circle-16" alt="">

            </div>
            <div class ="modal-total-form-info-user">
                <%=@user.email%>
            </div>
        </div>
        <div class="modal-total-form-content">
            <div class="modal-total-form-content-body">
                <div class ="modal-total-form-info-img">
                    <img src="<%= current_user.image%>" class="d-block w-40-m clip-circle-16" alt="">

                </div>
                <div class ="modal-total-form-info-user">
                    <%=@user.email%>
                </div>
                <div class="modal-total-form-content-body-style">
                    <%=@post.body%>
                </div>
            </div>
            
        </div>
        <div class="modal-total-form-button">
        a
        </div>
        <div class="modal-total-form-like">
        b
        </div>
        <div class="modal-total-form-comment">
c
        </div>
    </div>
    
</div>

app/views/instagram/index.html.erb
<style>
  .total-section{
    background:rgba(var(--b3f,250,250,250),1);
    min-height:888px;
  }
  .content-body{
    padding-top: 30px;
    width:fit-content;
    text-align: center;
    display:flex;
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
  }
  .content-item {
    width: 614px;
    margin-right: 28px;
    display: flex;
    flex-direction: column;
  }
  .user-item{
    width : 293px;
    display:flex;
    flex-direction: column;
  }
  .post_form{
    margin : 2px auto;
  }
  .user_section{
  }
  .post-group-item{
    border: 0px;
    padding : 0px;
    margin-bottom:55px;
  }
  .list-group-item{
    border: 0px;
    padding : 0px;
    margin-bottom:4px;
  }
  
  .clip-circle-30 {
    clip-path: circle(30px at center);
  }
  .w-20 {
    width: 20%!important;
  }
  .padding-15{
    padding: 16px 0 16px 0;
  }
  .my-user{
    margin-top:18px;
    margin-bottom:10px;
    height:64px;
    display:flex;
  }
  .w-64{
    width: 64px!important;
    margin-right:20px;
  }
  .my-user-id{
    align-self:center;
    height:64px;
    line-height:60px;
  }
  .my-user-id-font{
    font-weight:600;
    font-size:14px;
    color:black;
  }
  .w-32-m{
    width: 32px!important;
    margin-right:12px;
    height:32px;
  }
  .clip-circle-16 {
    clip-path: circle(16px at center);
  }
  .follow-user-list{
    display:flex;
    padding:8px 0px 8px 8px;
  }
  .my-user-id-font-reco{
    font-weight:600;
    font-size:14px;
    color:black;
  }
  .my-user-id-font-reco-follow{
    font-weight:600;
    font-size:12px;
    color:#0095f6;
    text-align:right;
    width:48px;
  }
  .my-user-follow{
    font-weight:600;
    font-size:14px;
    width:180px;
    text-align:left;
  }
  .recommend-men{
    margin-top:22px;
    padding : 4px 16px 4px 0px;
    text-align:left;
    color:#8e8e8e;
    font-weight:600;
    font-size:14px;
  }
</style>
<div class="total-section">
  <div class ="content-body">
    <div class="content-item">
      <%if current_user.present?%>
        <% if @post.size == 0%>
          <div>
            게시물이 없습니다.
          </div>
        <%else%>
          <div class=list-group>
          <%@post.each do |post|%>
            <div class="post-group-item">
              <%= render 'form', post: post, user: User.where(id:post.user_id) %>
            </div>
          <%end%>
          </div>
        <%end%>
      <%else%>
        <div>
          로그인이 필요합니다.
        </div>
      <%end%>
    </div>
    <div class ="user-item">
      <div class ="user_section">
        <div class ="user_info">
          <%if current_user.present?%>
            <div class ="my-user">
              <div class="user_image">
                <%if current_user.image.present?%>
                  <img src="<%= current_user.image%>" class="d-block w-64 clip-circle-30" alt="">
                <%else%>
                  <img src="<%= "image/user.jpg"%>" class="d-block w-64 clip-circle-30" alt="">
                <%end%>
              </div>
              <div class="my-user-id">
                <%=link_to current_user.email, instagram_path(current_user.id), class:"my-user-id-font", style: 'color : black'%> 
              </div>
            </div>
            <div class="recommend-men">
              회원님을 위한 추천
            </div>
            <div class="user_list">
              <%=render 'user', users: User.where.not(id:current_user.id)%>
            </div>
          <%else%>
            로그인이 필요합니다.
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/instagram/onload.js.erb
location.reload(true);

app/views/instagram/show.html.erb
<style>
	.total-section{
		background:rgba(var(--b3f,250,250,250),1);
		min-height:888px;
	}
	.userpage-container{
		width:995px;
		text-align:center;
		padding-top:30px;
		padding-right: 30px;
		padding-left: 30px;
		margin-right: auto;
		margin-left: auto;
	}
	.userpage-userinfo{
		display:flex;
		height:150px;
		margin-bottom:44px;
	}
	.userpage-userinfo-form-userimg{
		width:290px;
		text-align: -webkit-center;
		margin-right:30px;
	}
	.userpage-userinfo-img{
		width: 150px!important;
		height:150px;
	}
	.userpage-userinfo-img-circle{
		clip-path: circle(75px at center);
	}
	
	.userpage-userinfo-form-info{
		margin-top:5px;
		height:40px;
		display: block;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		font-weight: 300;
		font-size: 28px;
		line-height: 32px;
		color: #262626;
		text-align:left;
	}
	.userpage-userinfo-form-count{
		display:flex;
		height:18px;
		margin:15px 0 20px 0;
	}
	.userpage-userinfo-form-count-each{
		width:77px;
		height:18px;
		margin-right:40px;
		display:flex;
	}
	.userpage-userinfo-form-count-each-num{
		font-weight:600;
	}
	.userpage-userinfo-form-usercomment{
		font-weight: 600;
    text-align: left;
	}
	.grid-container{
		display: flex;
 	 	flex-wrap: wrap;
		width:963px;
  		box-sizing: border-box;
	}
	.flex-item {
		max-width: 293px;
		flex-grow: 1;
		height: 293px;
		box-sizing: border-box;
		margin-right:28px;
		margin-bottom:28px;
		justify-content: space-between;
		text-align: center;
	}
	.post-image{
		width:293px!important;
		height:inherit;
	}
	.img-inner{
		top: -9999px;
		left: -9999px;
		right: -9999px;
		bottom: -9999px;
		margin: auto;
    }
	.vertical-alignment-helper {
		display:table;
		height: 100%;
		width: 100%;
		pointer-events:none; /* This makes sure that we can still click outside of the modal to close it */
	}
	.vertical-align-center {
		/* To center vertically */
		display: table-cell;
		vertical-align: middle;
		pointer-events:none;
	}
	.modal-content {
		/* Bootstrap sets the size of the modal in the modal-dialog class, we need to inherit it */
		width:935px;
		height:inherit;
		/* To center horizontally */
		margin: 0 auto;
		pointer-events: all;
	}
</style>
<div class="total-section">
	<div class="userpage-container">
		<div class="userpage-userinfo">
			<div class="userpage-userinfo-form-userimg">
				<%if @user.image.present?%>
					<img src="<%= @user.image%>" class="d-block userpage-userinfo-img userpage-userinfo-img-circle" alt="">
				<%else%>
					<img src="<%= "/image/user.jpg"%>" class="d-block  userpage-userinfo-img userpage-userinfo-img-circle" alt="">
				<%end%>
			</div>
			<div class="userpage-userinfo-form-rightpart">
				<div class="userpage-userinfo-form-info">
						<%=@user.email%>
				</div>
				<div class="userpage-userinfo-form-count">
					<div class="userpage-userinfo-form-count-each">
						<div>
							게시물 
						</div>
						&nbsp;
						<div class="userpage-userinfo-form-count-each-num">
							<%=Post.where(user_id:@user.id).size%>
						</div>
					</div>
					<div class="userpage-userinfo-form-count-each">
						<div>
							팔로워 
						</div>
						&nbsp;
						<div class="userpage-userinfo-form-count-each-num">
							<%=@user.follows.size%>
						</div>
					</div>
					<div class="userpage-userinfo-form-count-each">
						<div>
							팔로우 
						</div>
						&nbsp;
						<div class="userpage-userinfo-form-count-each-num">
							<%=@user.received_follows.size%>
						</div>
					</div>
				</div>
				<div class="userpage-userinfo-form-usercomment">
					myInstaID
				</div>
			</div>
		</div>
		<div style="height:53px; border-top:1px solid #dbdbdb">

		</div>
		<div>
			<div class="grid-container">
				<% @posts.each do |p|%>
					<div class="flex-item">
						<%= link_to view_instagram_index_path(id: p.id), remote:true, data:{target:'#modal-window',toggle:'modal'} do %>
							<img src="<%= p.images[0].image%>" class="post-image img-div img-inner">
						<% end %>
						<!-- Modal -->
						<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
							<div class="vertical-alignment-helper" role="document">
								<div class="modal-dialog vertical-align-center">
									<div class="modal-content">
									</div>
								</div>
							</div>
						</div>
					</div>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/instagram/view.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'instagram/view'%>");
$("#modal-window").modal('show');