config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "home#index"
  get "/pokemon" => "pokemon#index"
  get "/pokemon/volt" => "pokemon#volt"
  post "/pokemon/speed" => "pokemon#speed"

  # get "/posts/my" => "posts#my"
  
  resources :posts do
    collection do
      get :my
    end
    member do  
    end
    resources :like do
      collection do
        get :check
      end
    end
  end

  resources :comments

  resources :instagram do
    collection do
      get :check
      get :check_follow
      get :view
    end
  end
 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional:true
  belongs_to :post, optional:true
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :post, optional: true

  def image_url
    self.image.image_url
  end
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user, optional:true
  belongs_to :post, optional:true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional:true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :nullify
  has_many :likes
  has_many :like_posts, through: :likes, source: :post
  
  # following
  has_many :follows, dependent: :destroy
  has_many :followings, through: :follows, source: :target

  # follower
  has_many :received_follows, class_name: "Follow", foreign_key: :target_id, dependent: :destroy
  has_many :followers, through: :received_follows, source: :user

  mount_uploader :image, ImageUploader


  def liked? post_id=nil
    self.likes.find_by(post_id: post_id).present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      @posts=Post.all
      if current_user
        @user=current_user
        @favorate_posts=Post.where
      else
        @user="게스트"
      end
    end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
	def check
		like=current_user.likes.find_by(post_id: params[:post_id])
		
		if like.present?
			like.destroy
			#redirect_to post_path(params[:post_id])
		else
			Like.create like_params
			#redirect_to post_path(params[:post_id])

		end
	end
	private
	def like_params
		{user_id: current_user.id, post_id: params[:post_id]}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/instagram_comments/_comment.html.erb
<% comment ||= nil %>
<% if comment %>
  <div class="list-group-item post-content-body-margin" id="comment-<%= comment.id %>">
    <div class="row">
      <div class="text-weight">
        <%=link_to comment.user.email, instagram_path(comment.user.id), class:"my-user-id-font", style: 'color : black'%>
      </div>
      &nbsp;
      <div class="text-content-weight">
        <%= comment.body %>
      </div>
      <div>
      </div>
    </div>
  </div>
<% end %>

app/views/instagram_comments/_comments.html.erb
<% comments ||= [] %>

<div class="list-group-comment card-text">
  <% if comments.present? %>
    <% comments.each do |comment| %>
      <%= render 'instagram_comments/comment', comment: comment %>
    <% end %>
  <% else %>
    
  <% end %>
</div>

app/views/instagram_comments/_form.html.erb
<% comment ||= nil %>
<% post ||= nil %>
<% user ||= nil %>
<% if comment && post && user %>
  <div class="comment-form-style">
    <%= form_for(comment, :html => { :style => 'display:flex;' }, remote: true) do |c|%>
      <%= c.text_area(:body,class: 'comment-form-body' ,placeholder: "댓글 달기...") %>

      <%= c.hidden_field :post_id, value:post.id %>
      <%= c.hidden_field :user_id, value: user.id%>
      <%= hidden_field_tag 'instagram', true %>
      <%= c.button "게시", :submit => "",  class: "btn comment-submit-button-style" %>
    <%end%>
  </div>
<%end%>

app/views/instagram_comments/create.js.erb
$("#comment_body").val("");
$(".list-group-comment").append("<%= j(render('instagram_comments/comment', comment: @comment)) %>")

app/views/instagram_comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%if controller_name=="instagram"%>
      <title>instagram</title>
    <%else%>
      <title>First Rails</title>
    <%end%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag('application') %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
      a {
        text-decoration: unset !important;
      }
    </style>
  </head>

  <body>
    <% if controller_name=="instagram"%>
      <%=render 'shared/instagram_header'%>
    <% else%>
      <%=render 'shared/header'%>
    <%end%>
    <% if controller_name!="instagram"%>
      <div class="container">
        <%= yield %> 
      </div>
    <%else%>
      <%= yield %> 
    <%end%>
  </body>
</html>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container">
    <a class="navbar-brand font-weight-bold" href="<%= root_path%>">
      <h3 class="text-white">내 홈페이지</h3>    
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item text-white nav-link <%="active" if(controller_name=="posts") %>" href="<%=posts_path%>"> 블로그 </a>
      </div>
      <div class="navbar-nav">
        <a class="nav-item text-white nav-link <%="active" if(controller_name=="instagram") %>" href="<%=instagram_index_path%>"> 인스타그램 </a>
      </div>
      <%if current_user%>
        <div class="navbar-nav">
          <%=link_to "로그아웃", destroy_user_session_path, method: :delete, class: "text-white"%>
        </div>
      <%else%>
        <div class="navbar-nav">
          <%=link_to "로그인", new_user_session_path, class:"text-white" %>
        </div>
      <%end%>
    </div>
  </div>
</nav>

app/views/shared/_instagram_header.html.erb
<style>
  .navbar
  {
    border-bottom: 1px solid #0f0f0f36;
    height :54px;
    padding: 0px;
  }
  .nav-search{
    text-align : center;    
    height: 25px;

  }
  .container-nav{
    height: inherit;
    text-align: center;
    width:935px;
    
    margin-right: auto;
    margin-left: auto;
    display:flex;
    justify-content:space-between;
    align-items:center;
  }
</style>
<nav class="navbar .navbar-fixed-top">
  <div class="container-nav">
    <a href="<%= instagram_index_path%>">
      <img src="<%= "/image/logo.png"%>" >
    </a>
    
    <form class="navbar-form navbar-center" action="/">
      <div class="input-group">
        <input type="text" class="form-control nav-search" placeholder="검색" name="search">
      </div>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <%if current_user.present?%>
        <ul><%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "text-black" %> </a></ul>
      <%else%>
        <ul><%=link_to "로그인", new_user_session_path, class:"text-black" %> </a></ul>
      <%end%>
      
    </ul>
  </div>
</nav>